{% set base_name = "libignition-transport" %}
{% set version = "8.1.0" %}
{% set major_version = version.split('.')[0] %}
{% set name = base_name + major_version %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/ignitionrobotics/ign-transport/archive/ignition-transport{{ major_version }}_{{ version }}.tar.gz
    sha256: caea46e51e9ebb4ad27f12ad004ed98d7b4011b601c07e6680c702f19da5cadb

build:
  number: 1
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}              # [not win]
    - {{ compiler('c') }}                # [not win]
    - vs2017_win-64                      # [win64]
    - vs2017_win-32                      # [win32]
    - make                               # [not win]
    - cmake
    - pkg-config
  host:
    - libignition-msgs5
    - cppzmq
    - zeromq
    - libuuid                            # [not win]
    - libprotobuf                        # [not win]
  run:
    - libignition-msgs5
    - cppzmq
    - zeromq
    - libuuid                            # [not win]
    - libprotobuf                        # [not win]

test:
  commands:
    - test -f ${PREFIX}/include/ignition/transport{{ major_version }}/ignition/transport.hh  # [not win]
    - test -f ${PREFIX}/lib/libignition-transport{{ major_version }}.so  # [linux]
    - test -f ${PREFIX}/lib/libignition-transport{{ major_version }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/cmake/ignition-transport{{ major_version }}/ignition-transport{{ major_version }}-config.cmake  # [not win]
    - if exist %PREFIX%\\Library\\include\\ignition\\transport{{ major_version }}\\ignition\\transport.hh (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\lib\\ignition-transport{{ major_version }}.lib (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\bin\\ignition-transport{{ major_version }}.dll (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\lib\\cmake\\ignition-transport{{ major_version }}\\ignition-transport{{ major_version }}-config.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/ignitionrobotics/ign-transport
  license: Apache-2.0
  license_file: LICENSE
  summary: Ignition Transport

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
    - traversaro
    - j-rivero
